############# English navigation ##############

# main menu
[[main]]
name = "Quiénes somos"
url = "/"
weight = 1

[[main]]
name = "Servicios"
url = "/servicios"
weight = 2

[[main]]
name = "Clientes"
url = "/clientes"
weight = 3

[[main]]
name = "Contacto"
url = "/contact"
weight = 4


# footer menu
[[footer]]
name = "Quiénes somos"
url = "/"
weight = 1

[[footer]]
name = "Servicios"
url = "/servicios"
weight = 2

[[footer]]
name = "Clientes"
url = "/clientes"
weight = 3

[[footer]]
name = "Contacto"
url = "/contact"
weight = 4
